site_name: Statistics
site_url: https://github.com/WonyoungCho/Statistics
site_description: Statistics
repo_url: https://github.com/WonyoungCho/Statistics/
site_author: Wonyoung Cho

extra_javascript: [docs.js]

pages:
    - Home: 'index.md'
    - Algorithm : 'algorithm.md'
    - Basics: 
        - 'Terminology' : 'terminology.md'
        - 'Statistics'  : 'basic.md'
    - R-studio: 'R.md'
    - Analysis: 'analysis.md'
    - Excel: 'excel.md'
theme: readthedocs
